# Generated by Django 3.2.5 on 2021-07-30 13:50

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='donor',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Format: +8801537377302', max_length=128, region=None),
        ),
    ]
