# Generated by Django 3.2.5 on 2021-07-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210730_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
        migrations.AddField(
            model_name='donor',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('other', 'Other'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
